name: Deploy Website to cPanel

on:
  push:
    branches: [ main ]

jobs:
  web-deploy:
    name: Build & Deploy to cPanel
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Upload via LFTP
      run: |
        sudo apt-get update && sudo apt-get install -y lftp
        lftp -c "
        set ftp:ssl-allow no;
        open -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} ${{ secrets.FTP_SERVER }};
        mirror --reverse --delete --verbose ./dist/ ./;
        quit;
        "
